### ISSUE TITLE
VideoSnapshot output is invalid on S10+

### ISSUE THREAD

**Issue by kingstone59** [natario1/CameraView#449]
### Describe the bug
I record snapshot video and the result has issue when playback (black screen, duration -104hours, sound ok) :
exoplayer : Top bit not zero
ffprobe: Invalid SampleDelta -413962640 in STTS, at 0 st:0

Device : SGS10+ SM-G975F (Android 9)
Lib : 2.0.0-beta04
VideoCodec.H_264

No issue with other device

**Comment by BlindJerobine** [comment]
Same issue with Pixel 2XL. The whole video is the first frame, duration 4h.

**Comment by HBiSoft** [comment]
@BlindJerobine Can you check at the bottom of #425, your device is one of the devices I experience an issue with when using this library, can you please confirm if you get the same error when recording a video?

**Comment by BlindJerobine** [comment]
@HBiSoft I don't get any error message. The video does simply contain the first frame for 4 hours. If I start takeVideoSnapshot(file), it stops after the first frame automatically, if I start takeVideoSnapshot(file, duration), it can run until the duration, but contains only the first frame, too.

This is my log when I record without duration:

I/OMXClient: IOmx service obtained
I/OMXClient: IOmx service obtained
W/OMXUtils: do not know color format 0x7fa30c06 = 2141391878
W/OMXUtils: do not know color format 0x7fa30c04 = 2141391876
W/OMXUtils: do not know color format 0x7fa30c08 = 2141391880
W/OMXUtils: do not know color format 0x7fa30c07 = 2141391879
W/OMXUtils: do not know color format 0x7f000789 = 2130708361
I/ACodec: setupAVCEncoderParameters with [profile: Baseline] [level: Level4]
I/ACodec: [OMX.qcom.video.encoder.avc] cannot encode HDR static metadata. Ignoring.
I/ACodec: setupVideoEncoder succeeded
W/OMXUtils: do not know color format 0x7f000789 = 2130708361
E/EglBaseSurface: ROTBUG eglSurfaceWidth: 850 eglSurfaceHeight: 1600
D/ACodec: dataspace changed to 0x10c10000 (R:2(Limited), P:3(BT601_6_625), M:3(BT601_6), T:3(SMPTE170M)) (R:2(Limited), S:2(BT601_625), T:3(SMPTE_170M))
I/MPEG4Writer: limits: 4294967295/0 bytes/us, bit rate: -1 bps and the estimated moov size 3191 bytes
I/MPEG4Writer: setStartTimestampUs: 164685834080
I/MPEG4Writer: Earliest track starting time: 164685834080
I/MPEG4Writer: setStartTimestampUs: 120097639255
I/MPEG4Writer: Earliest track starting time: 120097639255
D/MPEG4Writer: Audio track stopping. Stop source
I/MPEG4Writer: Received total/0-length (7/0) buffers and encoded 7 frames. - Video
D/MPEG4Writer: Audio track source stopping
D/MPEG4Writer: Audio track source stopped
I/MPEG4Writer: Received total/0-length (4/0) buffers and encoded 4 frames. - Audio
I/MPEG4Writer: Audio track drift time: 0 us
D/MPEG4Writer: Audio track stopped. Stop source
D/MPEG4Writer: Video track stopping. Stop source
D/MPEG4Writer: Video track source stopping
D/MPEG4Writer: Video track source stopped
D/MPEG4Writer: Video track stopped. Stop source
D/MPEG4Writer: Duration from tracks range is [92879, 44588427971] us
D/MPEG4Writer: Stopping writer thread
D/MPEG4Writer: 0 chunks are written in the last batch
D/MPEG4Writer: Writer thread stopped
I/MPEG4Writer: Ajust the moov start time from 120097639255 us -> 120097639255 us
D/MPEG4Writer: Audio track stopping. Stop source
D/MPEG4Writer: Video track stopping. Stop source

**Comment by HBiSoft** [comment]
@BlindJerobine Have you tried taking a video instead of a VideoSnapshot? I know it's not what you are trying to do, but I'm trying to figure out if it is something related to your device.. If you can, try taking a video and see if `onCameraError ` is called.

**Comment by BlindJerobine** [comment]
@HBiSoft If I set it to takeVideo(file), I get this message:

D/Camera: app passed NULL surface
E/MediaRecorder: setParameters(max-duration=10) failed: -22
E/AndroidRuntime: FATAL EXCEPTION: CameraViewController
    Process: de.blindjerobine.example, PID: 8066
    java.lang.RuntimeException: setMaxDuration failed.
        at android.media.MediaRecorder.setMaxDuration(Native Method)
        at com.otaliastudios.cameraview.FullVideoRecorder.start(FullVideoRecorder.java:85)
        at com.otaliastudios.cameraview.Camera1$14.run(Camera1.java:698)
        at com.otaliastudios.cameraview.Camera1$2.run(Camera1.java:62)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
E/CameraController: uncaughtException: Unexpected exception: java.lang.RuntimeException: setMaxDuration failed.
    java.lang.RuntimeException: setMaxDuration failed.
        at android.media.MediaRecorder.setMaxDuration(Native Method)
        at com.otaliastudios.cameraview.FullVideoRecorder.start(FullVideoRecorder.java:85)
        at com.otaliastudios.cameraview.Camera1$14.run(Camera1.java:698)
        at com.otaliastudios.cameraview.Camera1$2.run(Camera1.java:62)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
E/MediaRecorder: stop called in an invalid state: 4
E/CAMERA_FRAGMENT: com.otaliastudios.cameraview.CameraException
W/System.err: com.otaliastudios.cameraview.CameraException
W/System.err:     at com.otaliastudios.cameraview.Camera1.onVideoResult(Camera1.java:656)
W/System.err:     at com.otaliastudios.cameraview.VideoRecorder.dispatchResult(VideoRecorder.java:28)
W/System.err:     at com.otaliastudios.cameraview.FullVideoRecorder.stop(FullVideoRecorder.java:132)
W/System.err:     at com.otaliastudios.cameraview.Camera1.onStop(Camera1.java:286)
W/System.err:     at com.otaliastudios.cameraview.CameraController.stopImmediately(CameraController.java:223)
W/System.err:     at com.otaliastudios.cameraview.CameraController.destroy(CameraController.java:161)
W/System.err:     at com.otaliastudios.cameraview.CameraController.uncaughtException(CameraController.java:122)
W/System.err:     at java.lang.Thread.dispatchUncaughtException(Thread.java:1955)
D/Camera: app passed NULL surface
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.blindjerobine.example, PID: 8066
    java.lang.RuntimeException: setMaxDuration failed.
        at android.media.MediaRecorder.setMaxDuration(Native Method)
        at com.otaliastudios.cameraview.FullVideoRecorder.start(FullVideoRecorder.java:85)
        at com.otaliastudios.cameraview.Camera1$14.run(Camera1.java:698)
        at com.otaliastudios.cameraview.Camera1$2.run(Camera1.java:62)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by HBiSoft** [comment]
@BlindJerobine Did you set `setMaxDuration`? The error seems to come from `setMaxDuration`.

**Comment by BlindJerobine** [comment]
@HBiSoft I used

app:cameraVideoMaxDuration="10"

in my XML layout.

**Comment by HBiSoft** [comment]
@BlindJerobine Try and remove it and see what happens?

**Comment by BlindJerobine** [comment]
@HBiSoft I just tried a little bit, if I set it big enough (I tried 10000), it does not throw any error anymore.

**Comment by HBiSoft** [comment]
@BlindJerobine Okay so you can record and the file is created?

**Comment by BlindJerobine** [comment]
@HBiSoft Yes I can and yes it is. It's relatively big (48MB), but if I wanted to use takeVideo I would be very happy right now. :D

**Comment by HBiSoft** [comment]
@BlindJerobine Had to make sure its not related to your device..

**Comment by giusprenc** [comment]
Hi;

same issue with Huawei Mate 20 Pro (2.0.0-beta05).

Regards,


G.

**Comment by natario1** [comment]
I believe this is fixed in `master` now.

**Comment by vishnusp** [comment]
@natario1 Tried with `CameraView 2.0.0` in Moto G4 Plus with Android 7.0. 
The issue persists! 
Unable to view/play the recorded video.
